### ISSUE TITLE
parseUrl promise not working

### ISSUE THREAD

**Issue by janober** [glennjones/microformat-node#19]
Just wanted to try it out and did run the parseUrl-promise example. However it did always error with "TypeError: Cannot call method 'then' of undefined"

After checking the source code I saw that the "parseUrl" does not return a promise. The return is actually simply commented out (https://github.com/glennjones/microformat-node/commit/5546247d3406daf3b9ad19e59ebb113e06cb2425). Is there a reason for that or did that happen by accident? If not the example should probably get removed.

**Comment by glennjones** [comment]
Hi took me ages to get around to this, but codebase has been updated. New lib is based on some work for Mozilla so will now hopefully be kept update. 

It has promises provide by using Bluebird, I have also built tests for all the promise interface so hopefully it will not break again without me noticing.

**Comment by janober** [comment]
Great thanks!
