### ISSUE TITLE
Can't find '../test/testWriter.js' from bin/microformat-node

### ISSUE THREAD

**Issue by voxpelli** [glennjones/microformat-node#25]
The likely cause is that `test/testWriter.js` was removed in: https://github.com/glennjones/microformat-node/commit/c44e1da9e77131f21d875a1b1b2b5bd64ff2f069

It means that `bin/microformat-node` refuses to start now though.

Not sure what function it played though so can't provide an easy PR to fix it unfortunately.

**Comment by glennjones** [comment]
The `test/testWriter.js` is no longer needed after the recent changes to the microformat test suite. It was use to update the mocha tests.  Sorry I just forgot to remove it from `bin/microformat-node`  I will do that now.

**Comment by voxpelli** [comment]
Guess this one can be closed then?
