### ISSUE TITLE
Update microformat-shiv dependency reference

### ISSUE THREAD

**Issue by richardcarls** [glennjones/microformat-node#28]
I am getting build errors with Travis-CI due to an intermittent 403 response from this api.github URL during `npm install`, even though it seems to install fine locally:
```json
"microformat-shiv": "https://api.github.com/repos/glennjones/microformat-shiv/tarball/"
```

Would you be opposed to using the owner/repo convention outlined [here](https://docs.npmjs.com/files/package.json#dependencies)?
```json
"microformat-shiv": "glennjones/microformat-shiv"
```

**Comment by glennjones** [comment]
Hi Richard, Thanks for the PR. I had to make some larger changes to get `microformat-node` to play nice with `microformat-shiv`. This change was roll into the latest update and is now in v2.x of `microformat-node`

Everything should now pass the tests, if you have any more problems let me known.
