### ISSUE TITLE
crash on certain input

### ISSUE THREAD

**Issue by Janpot** [glennjones/microformat-node#34]
following code crashes with a `TypeError: Cannot read property 'replace' of null`:

    var Microformats = require('microformat-node');
    Microformats.get({
      html: '<div class="include item"></div>'
    }, function (err, data) {
       console.log(err, data);
    });

also fails on input:

    '<div class="include"></div><div class="item"></div>'

narrowed down sample from http://www.advodata.be/

also happening on www.netflow.ro

**Comment by sebilasse** [comment]
@Janpot @glennjones : Fix proposed above ...

**Comment by glennjones** [comment]
Hi @Janpot thanks for finding this issue and providing the example and @sebilasse for providing the the fix. I have updated the underlying parsing and add a new test.

Its now in `microformats-node` v2.0.1

Any other problems let me known 

Glenn
