### ISSUE TITLE
crash on certain markup

### ISSUE THREAD

**Issue by Janpot** [glennjones/microformat-node#35]
Library crashes on following markup with a `TypeError: Cannot set property '0' of undefined`:

    var Microformats = require('microformat-node');
    Microformats.get({
      html: '<div class="hentry"><div class="dt-">0AM<div class="dt-">x</div></div></div>'
    }, function (err, data) {
       console.log(err, data);
    });

narrowed down sample from: http://lbpm.com/

also happening on www.nesbitts.com, www.browsbyfay.com, decijisajam.rs, phytocarestetica.com

**Comment by sebilasse** [comment]
@Janpot 
It is absolutely fine reporting this errors - will look into this one as well.

Regarding your 

> "also happening on"

: If you you use it in **production** :
Use it in a [`try {} catch (error) {}` block](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/try...catch) to return an empty mf-object instead of an Unknown Error

Your example above could become :

```js
var Microformats = require('microformat-node');
function getMFnoUnknownError(o, cb) {
  try {
    return Microformats.get(o, cb);
  } catch (err) {
    return (!(cb)) ? {"items":[{"type":["h-item"],"properties":{}}],"rels":{},"rel-urls":{}} :
    cb(null, );
  }
}
// same use as above :
getMFnoUnknownError({
  html: '<div class="hentry"><div class="dt-">0AM<div class="dt-">x</div></div></div>'
}, function (err, data) {
   console.log(err, data);
});
```

**Comment by Janpot** [comment]
@sebilasse I just dumbed the program down to the smallest possible code that reproduces the problem. It's nice of you to start teaching me how to code, but you're wasting your time here.

**Comment by voxpelli** [comment]
@Janpot Chill :) @sebilasse is just offering a workaround for you and others that experience this issue, no need to be rude. Strangers can't possibly know your skill level and even then – issues may affect more people than the one reporting it. Instead you could maybe check if #37 actually fixes this issue?

**Comment by sebilasse** [comment]
@Janpot You realized that I fixed both issue apart from saying "in production for foreign code always use try/catch". And as @voxpelli It is not about you it is about everyone. 
@voxpelli As always : Rude Open-Source-Consumers, nice indieweb-people ;)

**Comment by Janpot** [comment]
@sebilasse @voxpelli That's why I started by saying "It's nice of you to start teaching me how to code". Because I don't mean to be rude.

**Comment by Janpot** [comment]
You also might want to read http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by glennjones** [comment]
Hi @Janpot thanks for finding this issue and providing the example and @sebilasse for providing the the fix. I have updated the underlying parsing and add a new test.

Its now in `microformats-node` v2.0.1

Any other problems let me known 

Glenn
